# Generated by Django 3.2.4 on 2025-05-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack', to='skoulApi.pack'),
        ),
    ]
