# Generated by Django 3.2.4 on 2025-05-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=500)),
                ('pdf', models.FileField(null=True, upload_to='Cours/')),
            ],
        ),
        migrations.CreateModel(
            name='CoursAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skoulApi.classes')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skoulApi.courses')),
            ],
        ),
    ]
