# Generated by Django 3.2.4 on 2025-03-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('criticality', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
