# Generated by Django 3.2.4 on 2025-05-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0002_alter_classes_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsendmodel',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
