# Generated by Django 3.2.4 on 2025-05-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0003_emailsendmodel_is_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diffusionlist',
            old_name='email',
            new_name='recipients',
        ),
    ]
