# Generated by Django 3.2.4 on 2025-04-28 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skoulApi', '0004_auto_20250428_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='skoulApi.levelclass'),
        ),
    ]
